# PyTorch Basics: Tensors & Gradients
### Part 1 of "Deep Learning with Pytorch: Zero to GANs"

This tutorial covers the following topics:

* Introductions to PyTorch tensors
* Tensor operations and gradients
* Interoperability between PyTorch and Numpy
* How to use the PyTorch documentation site

In [2]:
import torch

In [7]:
# Creating tensors
# simple tensor
t1 = torch.tensor([1., 2, 3, 4])
print("t1 tensor:\n {}, \ntype: {}, dimentions: {}\n".format(t1, t1.dtype, t1.shape))

# three-dimentional tensor
t2 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
print("t2 tensor:\n {}, \ntype: {}, dimentions: {}".format(t2, t2.dtype, t2.shape))

t1 tensor:
 tensor([1., 2., 3., 4.]), 
type: torch.float32, dimentions: torch.Size([4])

t2 tensor:
 tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]]), 
type: torch.float32, dimentions: torch.Size([2, 2, 3])


In [10]:
# Tensor operations
# initialization
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

# arithmetic operationsn w.grad is short for gradient, which is another term for derivative. The term gradient is primarily used while dealing with vectors and matrice
y = w * x + b # 3 * 4 + 5 = 17
print("Result: ", y)

# compute derivatives
y.backward()
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

Result:  tensor(17., grad_fn=<AddBackward0>)
dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [24]:
# Tensor functions
# fill a tensor with some value
t_3 = torch.full((3, 5), 33)
print("t3 tensor: \n", t_3)

# fill a tensor with 1s
t_4 = torch.ones(3,5)
print("t4 tensor: \n", t_4)

t_5 = torch.cat((t_3, t_4))
print("t5 tensor: \n", t_5)

t_6 = t_5.reshape(5, 6)
print("t6 tensor: \n", t_6)

t3 tensor: 
 tensor([[33, 33, 33, 33, 33],
        [33, 33, 33, 33, 33],
        [33, 33, 33, 33, 33]])
t4 tensor: 
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
t5 tensor: 
 tensor([[33., 33., 33., 33., 33.],
        [33., 33., 33., 33., 33.],
        [33., 33., 33., 33., 33.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]])
t6 tensor: 
 tensor([[33., 33., 33., 33., 33., 33.],
        [33., 33., 33., 33., 33., 33.],
        [33., 33., 33.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.]])


In [25]:
# Interoperability with NumPy
import numpy as np

In [42]:
# conversion, numpy --> pytorch
x = np.array([[1, 2], [3, 4.]])
y = torch.from_numpy(x)
print("After conversion:\n{}".format(y))

# conversion, numpy <-- pytorch
z = y.numpy()
print("After conversion:\n{}\nType: {}".format(z, type(z)))

After conversion:
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
After conversion:
[[1. 2.]
 [3. 4.]]
Type: <class 'numpy.ndarray'>
