## Gradient Descent and Linear Regression with PyTorch

### Part 2 of "Deep Learning with Pytorch: Zero to GANs"
This tutorial covers the following topics:

- Introduction to linear regression and gradient descent
- Implementing a linear regression model using PyTorch tensors
- Training a linear regression model using the gradient descent algorithm
- Implementing gradient descent and linear regression using PyTorch built-in


In [ ]:
# Linear Regression From Scratch 

In [1]:
import numpy as np
import torch

In [2]:
# Training Data
# input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

# targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

# convert to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print("\n")
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])


tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [3]:
# Linear Regression
# set random weights and biases
w = torch.randn(2, 3, requires_grad=True) 
b = torch.randn(2, requires_grad=True)   
print("wegihts are:\n", w)
print("biases are:\n", b)

print("\n")
print("#########################################################")
print("\n")

# linear regression model
def model(x):
    return x @ w.t() + b # @ is matrix multiplication, .t is transpose

# predictions
preds = model(inputs)
print("Predictions: \n")
print(preds)

wegihts are:
 tensor([[ 1.0763,  1.3632,  0.2012],
        [ 0.6196, -1.5908,  2.2609]], requires_grad=True)
biases are:
 tensor([-1.0605, -0.2148], requires_grad=True)


#########################################################


Predictions: 

tensor([[177.4965,  35.6503],
        [229.7227,  60.8746],
        [286.9155, -28.3468],
        [174.7868,  78.2339],
        [218.1561,  48.0814]], grad_fn=<AddBackward0>)


In [4]:
# Evaluations
# MSE loss function
# (measn squared error)
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()
    # .numel() - number of elements, 10 in our case

# compute loss
loss = mse(preds, targets)
print(loss)

# interpretation
print("On average, each element in the prediction differs from the actual target by {:.2f}".format(loss.sqrt()))

tensor(13723.2578, grad_fn=<DivBackward0>)
On average, each element in the prediction differs from the actual target by 117.15


In [5]:
# Gradient Descent
# compute gradients
loss.backward() 

# set learning rate 
alpha = 1e-5

# updating weights and biases
with torch.no_grad(): # do not track, calculate, or modify gradients while updating w & b
    w -= w.grad * alpha
    b -= b.grad * alpha
    w.grad.zero_()
    b.grad.zero_()

# checking the result
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(9837.6797, grad_fn=<DivBackward0>)


Linear Regression With Gradient Descents Algorithm

1. Generate predictions

2. Calculate the loss

3. Compute gradients w.r.t the weights and biases

4. Adjust the weights by subtracting a small quantity proportional to the gradient

5. Reset the gradients to zero

6. Go back to step 1, repeat until certain accuracy is reached.

In [6]:
# Algorithm Implementation
# train for 300 epochs
for i in range(300):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

# calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print("loss values: ", loss)

# predictions
print("Predictions: \n", preds)

loss values:  tensor(154.8083, grad_fn=<DivBackward0>)
Predictions: 
 tensor([[ 58.5088,  71.6175],
        [ 78.1416, 112.3039],
        [125.7753, 104.3953],
        [ 29.4316,  45.9205],
        [ 89.7641, 134.1360]], grad_fn=<AddBackward0>)


In [ ]:
# Linear Regression Using PyTorch

In [12]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], 
                   [74, 66, 43], [91, 87, 65], [88, 134, 59], [101, 44, 37], [68, 96, 71], 
                   [73, 66, 44], [92, 87, 64], [87, 135, 57], [103, 43, 36], [68, 97, 70]], dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
                    [57, 69], [80, 102], [118, 132], [21, 38], [104, 118], 
                    [57, 69], [82, 100], [118, 134], [20, 38], [102, 120]], dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print("dimentions of inputs: {},\ndimentions of targets: {}".format(inputs.shape, targets.shape))

dimentions of inputs: torch.Size([15, 3]),
dimentions of targets: torch.Size([15, 2])


In [22]:
# Create Dataset and Dataloader
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [31]:
# define dataset
train_ds = TensorDataset(inputs, targets)
print("first 3 elements of the dataset: \n{}, \n{}\n".format(train_ds[0:3][0],train_ds[0:3][1]))

# define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

print("dataloader contains:")
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

first 3 elements of the dataset: 
tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.]]), 
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.]])

dataloader contains:
tensor([[ 87., 135.,  57.],
        [101.,  44.,  37.],
        [ 91.,  88.,  64.],
        [ 73.,  66.,  44.],
        [ 87., 134.,  58.]])
tensor([[118., 134.],
        [ 21.,  38.],
        [ 81., 101.],
        [ 57.,  69.],
        [119., 133.]])


In [40]:
# Import Linear Model, Loss Function & Optimizer
import torch.nn as nn
import torch.nn.functional as F

In [43]:
# define model (random w & b)
model = nn.Linear(3, 2)
# print(list(model.parameters()))
# print("\n")

# Generate predictions
preds = model(inputs)

# define loss function
loss_fn = F.mse_loss
loss = loss_fn(model(inputs), targets)

# define optimizer (gradient descend)
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [44]:
# Applying The Algorithm
def fit(num_epochs, model, loss_fn, opt, train_dl):
    for epoch in range(num_epochs):
        for xb,yb in train_dl: # train for batches of data
            pred = model(xb)
            loss = loss_fn(pred, yb)
            loss.backward()
            opt.step() # updating gradients
            opt.zero_grad() # clearing gradients
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 992.8507
Epoch [20/100], Loss: 543.5728
Epoch [30/100], Loss: 160.7798
Epoch [40/100], Loss: 130.8488
Epoch [50/100], Loss: 369.6737
Epoch [60/100], Loss: 220.1362
Epoch [70/100], Loss: 172.9101
Epoch [80/100], Loss: 92.8416
Epoch [90/100], Loss: 45.9343
Epoch [100/100], Loss: 83.1875


In [45]:
# generate a prediction with our model
model(torch.tensor([[75, 63, 44.]]))

tensor([[55.8828, 68.8207]], grad_fn=<AddmmBackward>)